package com.GIHOSTINGS.giposapp;

import android.app.AlertDialog;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.Editable;
import android.text.InputType;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;
import java.util.List;
import java.util.Locale;

public class CheckoutActivity extends InsetActivity {
  private final int ink=Color.rgb(18,32,51),red=Color.rgb(199,22,55),muted=Color.rgb(99,115,138),teal=Color.rgb(8,127,140),line=Color.rgb(217,226,236),page=Color.rgb(244,247,250);
  private PosDatabase db;private PosDatabase.BusinessSettings billing;private String orderId,discountMode="amount",paymentMode="cash";private double payable;private boolean updating=false;
  private LinearLayout itemList,paymentModes,paymentFields;private EditText discountValue,cash,upi,card,due,cashReceived;private TextView itemSummary,subtotalText,taxText,discountText,totalText,remainingText,customerText;private Button discountTypeButton,saveButton,printButton;private PosDatabase.CustomerInfo customer;

  @Override public void onCreate(Bundle saved){super.onCreate(saved);if(!requireFeature("billing"))return;db=PosDatabase.get(this);billing=db.businessSettings();orderId=getIntent().getStringExtra("orderId");if(orderId==null||db.orderInfo(orderId)==null){finish();return;}build();refreshCheckout();}
  @Override protected void onResume(){super.onResume();if(itemList!=null)refreshCheckout();}
  private void build(){
    LinearLayout screen=column();screen.setBackgroundColor(page);
    LinearLayout head=row();head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(dp(16),dp(13),dp(16),dp(10));head.addView(AppBackButton.create(this,v->finish()),new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout title=column();title.setPadding(dp(11),0,0,0);title.addView(text("Checkout",24,ink,true));PosDatabase.OrderInfo info=db.orderInfo(orderId);title.addView(text(info.tableName.isEmpty()?"Current order":info.tableName,13,muted,false));head.addView(title,new LinearLayout.LayoutParams(0,-2,1));screen.addView(head);
    ScrollView scroll=new ScrollView(this);LinearLayout content=column();content.setPadding(dp(16),0,dp(16),dp(24));
    LinearLayout items=panel();LinearLayout itemHeading=row();itemHeading.setGravity(Gravity.CENTER_VERTICAL);LinearLayout itemCopy=column();itemCopy.addView(text("Order items",17,ink,true));itemSummary=text("Review quantities before payment",12,muted,false);itemCopy.addView(itemSummary,top(3));itemHeading.addView(itemCopy,new LinearLayout.LayoutParams(0,-2,1));items.addView(itemHeading);itemList=column();items.addView(itemList,top(8));content.addView(items);
    LinearLayout summary=panel();summary.addView(sectionHead("Bill summary","Amounts are calculated from saved order lines"));subtotalText=valueRow(summary,"Subtotal");taxText=valueRow(summary,"Tax");discountText=valueRow(summary,"Discount");View divider=new View(this);divider.setBackgroundColor(line);summary.addView(divider,topHeight(10,1));totalText=valueRow(summary,"Payable total");totalText.setTextSize(22);totalText.setTextColor(red);content.addView(summary);
    LinearLayout discount=panel();discount.addView(sectionHead("Discount","Enter a value only when this bill has a discount"));LinearLayout discountControl=row();discountControl.setGravity(Gravity.CENTER_VERTICAL);discountValue=amountInput("0.00");watch(discountValue);discountControl.addView(discountValue,new LinearLayout.LayoutParams(0,dp(56),1));discountTypeButton=button("Rs",teal,Color.WHITE);discountTypeButton.setMinWidth(0);discountTypeButton.setPadding(0,0,0,0);discountTypeButton.setContentDescription("Switch discount between amount and percentage");discountTypeButton.setOnClickListener(v->{discountMode="amount".equals(discountMode)?"percent":"amount";refreshDiscountType();refreshTotals();});LinearLayout.LayoutParams typeParams=new LinearLayout.LayoutParams(dp(64),dp(56));typeParams.leftMargin=dp(8);discountControl.addView(discountTypeButton,typeParams);discount.addView(discountControl,top(12));content.addView(discount,top(12));refreshDiscountType();
    LinearLayout payment=panel();payment.addView(sectionHead("Payment","Choose one method or split the amount"));paymentModes=row();payment.addView(paymentModes,top(10));paymentFields=column();payment.addView(paymentFields,top(12));remainingText=text("",13,muted,true);payment.addView(remainingText,top(10));customerText=text("No customer selected",14,ink,true);customerText.setPadding(dp(12),dp(12),dp(12),dp(12));customerText.setBackground(shape(Color.rgb(248,250,252),9,1,line));customerText.setOnClickListener(v->showCustomerPicker());payment.addView(customerText,top(10));content.addView(payment,top(12));refreshPaymentModes();
    scroll.addView(content);screen.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
    LinearLayout actions=row();actions.setPadding(dp(16),dp(10),dp(16),dp(14));actions.setBackground(shape(Color.WHITE,0,1,line));saveButton=button("Save Bill",Color.rgb(241,245,249),ink);saveButton.setOnClickListener(v->complete(false));actions.addView(saveButton,new LinearLayout.LayoutParams(0,dp(52),1));printButton=button("Save & Print",red,Color.WHITE);printButton.setOnClickListener(v->complete(true));LinearLayout.LayoutParams primary=new LinearLayout.LayoutParams(0,dp(52),1);primary.leftMargin=dp(10);actions.addView(printButton,primary);screen.addView(actions);setContentView(screen);
  }
  private void refreshCheckout(){refreshOrderItems();refreshTotals();}
  private void refreshOrderItems(){
    List<PosDatabase.OrderLine> lines=db.orderLines(orderId);itemList.removeAllViews();double quantity=0;for(PosDatabase.OrderLine lineItem:lines){quantity+=lineItem.quantity;itemList.addView(orderItemRow(lineItem),top(8));}
    itemSummary.setText(lines.isEmpty()?"No items in this order":formatQty(quantity)+" total qty  /  "+lines.size()+" line(s)");
    boolean ready=!lines.isEmpty();if(saveButton!=null)saveButton.setEnabled(ready);if(printButton!=null)printButton.setEnabled(ready);
    if(lines.isEmpty()){TextView empty=text("Add items before completing this bill.",14,muted,false);empty.setGravity(Gravity.CENTER);empty.setPadding(dp(12),dp(18),dp(12),dp(18));empty.setBackground(shape(Color.rgb(248,250,252),9,1,line));itemList.addView(empty);}
  }
  private View orderItemRow(PosDatabase.OrderLine lineItem){
    LinearLayout card=column();card.setPadding(dp(12),dp(11),dp(10),dp(11));card.setBackground(shape(Color.rgb(248,250,252),9,1,line));
    LinearLayout identity=row();identity.setGravity(Gravity.CENTER_VERTICAL);String name=lineItem.itemName+(lineItem.variantName.isEmpty()?"":"  /  "+lineItem.variantName);TextView itemName=text(name,15,ink,true);itemName.setMaxLines(2);identity.addView(itemName,new LinearLayout.LayoutParams(0,-2,1));ImageButton remove=new ImageButton(this);remove.setImageResource(android.R.drawable.ic_menu_delete);remove.setColorFilter(red);remove.setContentDescription("Delete "+lineItem.itemName);remove.setPadding(dp(10),dp(10),dp(10),dp(10));remove.setBackground(shape(Color.rgb(255,241,242),8,1,Color.rgb(254,205,211)));remove.setOnClickListener(v->confirmRemove(lineItem));LinearLayout.LayoutParams removeParams=new LinearLayout.LayoutParams(dp(42),dp(42));removeParams.leftMargin=dp(10);identity.addView(remove,removeParams);card.addView(identity);
    LinearLayout values=row();values.setGravity(Gravity.BOTTOM);values.setPadding(0,dp(9),0,0);LinearLayout quantityBox=column();quantityBox.addView(text("Qty",11,muted,true));LinearLayout controls=row();controls.setGravity(Gravity.CENTER_VERTICAL);Button minus=quantityButton("-",Color.WHITE,ink);minus.setContentDescription("Decrease "+lineItem.itemName);minus.setEnabled(lineItem.quantity>1);minus.setOnClickListener(v->{db.changeOrderLineQuantity(orderId,lineItem.id,-1);refreshCheckout();});controls.addView(minus,new LinearLayout.LayoutParams(dp(36),dp(36)));TextView count=text(formatQty(lineItem.quantity),14,ink,true);count.setGravity(Gravity.CENTER);controls.addView(count,new LinearLayout.LayoutParams(dp(42),dp(36)));Button plus=quantityButton("+",teal,Color.WHITE);plus.setContentDescription("Increase "+lineItem.itemName);plus.setOnClickListener(v->{db.changeOrderLineQuantity(orderId,lineItem.id,1);refreshCheckout();});controls.addView(plus,new LinearLayout.LayoutParams(dp(36),dp(36)));quantityBox.addView(controls,top(4));values.addView(quantityBox,new LinearLayout.LayoutParams(dp(114),-2));LinearLayout priceBox=amountColumn("Price","Rs. "+money(lineItem.unitPrice),Gravity.END);LinearLayout.LayoutParams priceParams=new LinearLayout.LayoutParams(0,-2,1);priceParams.leftMargin=dp(10);values.addView(priceBox,priceParams);LinearLayout amountBox=amountColumn("Amount","Rs. "+money(lineItem.lineTotal),Gravity.END);LinearLayout.LayoutParams amountParams=new LinearLayout.LayoutParams(0,-2,1);amountParams.leftMargin=dp(10);values.addView(amountBox,amountParams);card.addView(values);return card;
  }
  private LinearLayout amountColumn(String label,String value,int gravity){LinearLayout box=column();TextView heading=text(label,11,muted,true);heading.setGravity(gravity);box.addView(heading);TextView amount=text(value,14,ink,true);amount.setGravity(gravity);amount.setSingleLine(true);box.addView(amount,top(8));return box;}
  private void confirmRemove(PosDatabase.OrderLine lineItem){new AlertDialog.Builder(this).setTitle("Remove item?").setMessage(lineItem.itemName+" will be removed from this order.").setNegativeButton("Cancel",null).setPositiveButton("Remove",(dialog,which)->{db.removeOrderLine(orderId,lineItem.id);refreshCheckout();}).show();}
  private Button quantityButton(String label,int fill,int color){Button value=button(label,fill,color);value.setTextSize(18);value.setMinWidth(0);value.setMinimumWidth(0);value.setMinHeight(0);value.setMinimumHeight(0);value.setPadding(0,0,0,0);return value;}
  private void refreshDiscountType(){boolean percent="percent".equals(discountMode);discountTypeButton.setText(percent?"%":"Rs");discountTypeButton.setContentDescription(percent?"Percentage discount. Tap for amount":"Amount discount. Tap for percentage");discountValue.setHint(percent?"Discount percentage":"Discount amount");}
  private Button modeButton(String label,String value){boolean selected=value.equals(paymentMode);Button b=button(label,selected?teal:Color.WHITE,selected?Color.WHITE:ink);b.setTextSize(12);b.setOnClickListener(v->{paymentMode=value;refreshPaymentModes();});return b;}
  private void refreshPaymentModes(){paymentModes.removeAllViews();java.util.ArrayList<String> modes=new java.util.ArrayList<>(),labels=new java.util.ArrayList<>();modes.add("cash");labels.add("Cash");if(billing.upi){modes.add("upi");labels.add("UPI");}if(billing.card){modes.add("card");labels.add("Card");}if(billing.due){modes.add("due");labels.add("Due");}if(billing.split&&(billing.upi||billing.card||billing.due)){modes.add("split");labels.add("Split");}if(!modes.contains(paymentMode))paymentMode="cash";for(int i=0;i<modes.size();i++){if(i>0)paymentModes.addView(gap());paymentModes.addView(modeButton(labels.get(i),modes.get(i)),weight());}buildPaymentFields();}
  private void buildPaymentFields(){updating=true;paymentFields.removeAllViews();cash=upi=card=due=cashReceived=null;if("cash".equals(paymentMode)){cashReceived=amountInput("Cash received");cashReceived.setText(money(payable));watch(cashReceived);paymentFields.addView(labeled("Cash received",cashReceived));}else if("split".equals(paymentMode)){cash=amountInput("0.00");cashReceived=amountInput("0.00");watch(cash);watch(cashReceived);paymentFields.addView(labeled("Cash portion",cash));paymentFields.addView(labeled("Cash tendered",cashReceived),top(9));if(billing.upi){upi=amountInput("0.00");watch(upi);paymentFields.addView(labeled("UPI",upi),top(9));}if(billing.card){card=amountInput("0.00");watch(card);paymentFields.addView(labeled("Card",card),top(9));}if(billing.due){due=amountInput("0.00");watch(due);paymentFields.addView(labeled("Due",due),top(9));}}else paymentFields.addView(text("Rs. "+money(payable)+" will be recorded as "+paymentMode.toUpperCase(Locale.US)+".",14,ink,true));updating=false;refreshPaymentState();}
  private void refreshTotals(){try{PosDatabase.CheckoutTotals totals=db.checkoutTotals(orderId,discountMode,value(discountValue));payable=totals.payable;subtotalText.setText("Rs. "+money(totals.subtotal));taxText.setText("Rs. "+money(totals.tax));discountText.setText("− Rs. "+money(totals.discount));totalText.setText("Rs. "+money(totals.payable));if("cash".equals(paymentMode)&&cashReceived!=null&&!cashReceived.hasFocus()){updating=true;cashReceived.setText(money(payable));updating=false;}refreshPaymentState();}catch(Exception error){showError(error);}}
  private void refreshPaymentState(){if(remainingText==null)return;double allocated=0,balance=0,dueAmount=0;if("cash".equals(paymentMode)){double received=value(cashReceived);allocated=payable;balance=Math.max(0,received-payable);remainingText.setText("Balance  Rs. "+money(balance));}else if("split".equals(paymentMode)){allocated=value(cash)+value(upi)+value(card)+value(due);dueAmount=value(due);balance=Math.max(0,value(cashReceived)-value(cash));double remaining=payable-allocated;remainingText.setText((Math.abs(remaining)<0.005?"Fully allocated":"Remaining  Rs. "+money(remaining))+"    Balance  Rs. "+money(balance));}else{allocated=payable;dueAmount="due".equals(paymentMode)?payable:0;remainingText.setText("Fully allocated");}boolean needsCustomer=dueAmount>0;customerText.setVisibility(needsCustomer?View.VISIBLE:View.GONE);if(needsCustomer)customerText.setText(customer==null?"Select customer for due":customer.name+"  •  Due Rs. "+money(customer.dueBalance));}
  private void complete(boolean print){try{PosDatabase.CheckoutRequest request=request(print);setBusy(true);new Thread(()->{try{PosDatabase.CheckoutResult result=db.finalizeOrder(orderId,request);runOnUiThread(()->openSuccess(result));}catch(Exception error){runOnUiThread(()->{setBusy(false);showError(error);});}}).start();}catch(Exception error){showError(error);}}
  private PosDatabase.CheckoutRequest request(boolean print){double cashPart=0,upiPart=0,cardPart=0,duePart=0,tendered=0;if("cash".equals(paymentMode)){cashPart=payable;tendered=value(cashReceived);if(tendered+0.005<payable)throw new IllegalStateException("Cash received is less than the bill total");}else if("upi".equals(paymentMode))upiPart=payable;else if("card".equals(paymentMode))cardPart=payable;else if("due".equals(paymentMode))duePart=payable;else{cashPart=value(cash);upiPart=value(upi);cardPart=value(card);duePart=value(due);tendered=value(cashReceived);if(Math.abs((cashPart+upiPart+cardPart+duePart)-payable)>0.005)throw new IllegalStateException("Split amounts must exactly match the bill total");if(cashPart>0&&tendered+0.005<cashPart)throw new IllegalStateException("Cash tendered is less than the cash portion");}if(duePart>0&&customer==null)throw new IllegalStateException("Select a customer for the due amount");return new PosDatabase.CheckoutRequest(discountMode,value(discountValue),customer==null?"":customer.id,cashPart,upiPart,cardPart,duePart,tendered,print);}
  private void openSuccess(PosDatabase.CheckoutResult result){if(result.printQueued)PrintDispatcher.processAsync(this);CloudSyncManager.syncAsync(this);Intent intent=new Intent(this,SaleSuccessActivity.class);intent.putExtra("orderId",orderId);intent.putExtra("printQueued",result.printQueued);startActivity(intent);finish();}
  private void setBusy(boolean busy){saveButton.setEnabled(!busy);printButton.setEnabled(!busy);printButton.setText(busy?"Saving...":"Save & Print");}

  private void showCustomerPicker(){LinearLayout box=FormControls.dialogForm(this);EditText query=input("Search by name or phone",InputType.TYPE_CLASS_TEXT);box.addView(FormControls.field(this,"Find customer",query));LinearLayout results=column();ScrollView resultScroll=new ScrollView(this);resultScroll.addView(results);LinearLayout.LayoutParams resultParams=new LinearLayout.LayoutParams(-1,dp(220));resultParams.topMargin=dp(10);box.addView(resultScroll,resultParams);Button add=button("+ New Customer",Color.rgb(241,245,249),ink);box.addView(add,top(8));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Select customer").setView(box).setNegativeButton("Close",null).create();Runnable reload=()->renderCustomers(results,db.customers(query.getText().toString()),dialog);query.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){reload.run();}public void afterTextChanged(Editable e){}});add.setOnClickListener(v->showNewCustomer(dialog));dialog.setOnShowListener(v->reload.run());dialog.show();}
  private void renderCustomers(LinearLayout target,List<PosDatabase.CustomerInfo> values,AlertDialog dialog){target.removeAllViews();if(values.isEmpty()){target.addView(text("No matching customer",14,muted,false),top(16));return;}for(PosDatabase.CustomerInfo value:values){TextView row=text(value.name+"\n"+(value.phone.isEmpty()?"No phone":value.phone)+"  •  Due Rs. "+money(value.dueBalance),15,ink,true);row.setPadding(dp(12),dp(10),dp(12),dp(10));row.setBackground(shape(Color.WHITE,9,1,line));row.setOnClickListener(v->{customer=value;dialog.dismiss();refreshPaymentState();});target.addView(row,top(7));}}
  private void showNewCustomer(AlertDialog parent){LinearLayout form=FormControls.dialogForm(this);EditText name=input("Enter customer name",InputType.TYPE_CLASS_TEXT),phone=input("Enter phone number",InputType.TYPE_CLASS_PHONE),address=FormControls.multiline(this,"Enter address (optional)");form.addView(FormControls.field(this,"Customer name",name));form.addView(FormControls.field(this,"Phone number",phone),top(13));form.addView(FormControls.field(this,"Address",address),top(13));new AlertDialog.Builder(this).setTitle("New customer").setView(form).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{try{String id=db.saveCustomer(name.getText().toString(),phone.getText().toString(),address.getText().toString());for(PosDatabase.CustomerInfo found:db.customers(phone.getText().toString()))if(found.id.equals(id)){customer=found;break;}parent.dismiss();refreshPaymentState();}catch(Exception error){showError(error);}}).show();}

  private void watch(EditText field){if(field==null)return;field.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){if(updating)return;if(field==discountValue)refreshTotals();else refreshPaymentState();}public void afterTextChanged(Editable e){}});}
  private double value(EditText field){if(field==null)return 0;try{return Math.max(0,Double.parseDouble(field.getText().toString().trim()));}catch(Exception ignored){return 0;}}
  private void showError(Throwable error){Toast.makeText(this,error.getMessage()==null?"Could not complete billing":error.getMessage(),Toast.LENGTH_LONG).show();}
  private TextView valueRow(LinearLayout parent,String label){LinearLayout row=row();row.setGravity(Gravity.CENTER_VERTICAL);row.addView(text(label,14,muted,false),new LinearLayout.LayoutParams(0,-2,1));TextView value=text("Rs. 0.00",16,ink,true);row.addView(value);parent.addView(row,top(9));return value;}
  private LinearLayout sectionHead(String title,String detail){LinearLayout box=column();box.addView(text(title,17,ink,true));box.addView(text(detail,12,muted,false),top(3));return box;}
  private LinearLayout panel(){LinearLayout p=column();p.setPadding(dp(14),dp(14),dp(14),dp(14));p.setBackground(shape(Color.WHITE,10,1,line));return p;}private LinearLayout labeled(String label,View input){return FormControls.field(this,label,input);}private EditText amountInput(String hint){return input(hint,InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);}private EditText input(String hint,int type){return FormControls.input(this,hint,type);}
  private LinearLayout column(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);return v;}private LinearLayout row(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.HORIZONTAL);return v;}private TextView text(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(Typeface.DEFAULT_BOLD);return v;}private Button button(String s,int fill,int color){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(color);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(shape(fill,9,1,line));return b;}private GradientDrawable shape(int fill,int radius,int stroke,int strokeColor){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(stroke>0)d.setStroke(dp(stroke),strokeColor);return d;}private LinearLayout.LayoutParams top(int m){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(m);return p;}private LinearLayout.LayoutParams topHeight(int m,int h){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(h));p.topMargin=dp(m);return p;}private LinearLayout.LayoutParams weight(){return new LinearLayout.LayoutParams(0,dp(44),1);}private View gap(){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(dp(6),1));return v;}private String money(double v){return String.format(Locale.US,"%.2f",v);}private String formatQty(double v){return Math.rint(v)==v?String.valueOf((long)v):String.format(Locale.US,"%.2f",v);}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density);}
}
