package com.GIHOSTINGS.giposapp;

import android.app.AlertDialog;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.Editable;
import android.text.InputType;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;
import java.util.List;
import java.util.Locale;

public class CheckoutActivity extends InsetActivity {
  private final int ink=Color.rgb(18,32,51),red=Color.rgb(199,22,55),muted=Color.rgb(99,115,138),teal=Color.rgb(8,127,140),line=Color.rgb(217,226,236),page=Color.rgb(244,247,250);
  private PosDatabase db;private PosDatabase.BusinessSettings billing;private String orderId,discountMode="none",paymentMode="cash";private double payable;private boolean updating=false;
  private LinearLayout discountModes,paymentModes,discountField,paymentFields;private EditText discountValue,cash,upi,card,due,cashReceived;private TextView subtotalText,taxText,discountText,totalText,remainingText,customerText;private Button saveButton,printButton;private PosDatabase.CustomerInfo customer;

  @Override public void onCreate(Bundle saved){super.onCreate(saved);if(!requireFeature("billing"))return;db=PosDatabase.get(this);billing=db.businessSettings();orderId=getIntent().getStringExtra("orderId");if(orderId==null||db.orderInfo(orderId)==null){finish();return;}build();refreshTotals();}
  private void build(){
    LinearLayout screen=column();screen.setBackgroundColor(page);
    LinearLayout head=row();head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(dp(16),dp(13),dp(16),dp(10));Button back=button("‹",Color.WHITE,ink);back.setTextSize(22);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout title=column();title.setPadding(dp(11),0,0,0);title.addView(text("Checkout",24,ink,true));PosDatabase.OrderInfo info=db.orderInfo(orderId);title.addView(text(info.tableName.isEmpty()?"Current order":info.tableName,13,muted,false));head.addView(title,new LinearLayout.LayoutParams(0,-2,1));screen.addView(head);
    ScrollView scroll=new ScrollView(this);LinearLayout content=column();content.setPadding(dp(16),0,dp(16),dp(24));
    LinearLayout summary=panel();summary.addView(sectionHead("Bill summary","Amounts are calculated from saved order lines"));subtotalText=valueRow(summary,"Subtotal");taxText=valueRow(summary,"Tax");discountText=valueRow(summary,"Discount");View divider=new View(this);divider.setBackgroundColor(line);summary.addView(divider,topHeight(10,1));totalText=valueRow(summary,"Payable total");totalText.setTextSize(22);totalText.setTextColor(red);content.addView(summary);
    LinearLayout discount=panel();discount.addView(sectionHead("Discount","Applied to the final payable amount"));discountModes=row();discount.addView(discountModes,top(10));discountValue=amountInput("Discount value");watch(discountValue);discountField=labeled("Value",discountValue);discount.addView(discountField,top(10));content.addView(discount,top(12));refreshDiscountModes();
    LinearLayout payment=panel();payment.addView(sectionHead("Payment","Choose one method or split the amount"));paymentModes=row();payment.addView(paymentModes,top(10));paymentFields=column();payment.addView(paymentFields,top(12));remainingText=text("",13,muted,true);payment.addView(remainingText,top(10));customerText=text("No customer selected",14,ink,true);customerText.setPadding(dp(12),dp(12),dp(12),dp(12));customerText.setBackground(shape(Color.rgb(248,250,252),9,1,line));customerText.setOnClickListener(v->showCustomerPicker());payment.addView(customerText,top(10));content.addView(payment,top(12));refreshPaymentModes();
    scroll.addView(content);screen.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
    LinearLayout actions=row();actions.setPadding(dp(16),dp(10),dp(16),dp(14));actions.setBackground(shape(Color.WHITE,0,1,line));saveButton=button("Save Bill",Color.rgb(241,245,249),ink);saveButton.setOnClickListener(v->complete(false));actions.addView(saveButton,new LinearLayout.LayoutParams(0,dp(52),1));printButton=button("Save & Print",red,Color.WHITE);printButton.setOnClickListener(v->complete(true));LinearLayout.LayoutParams primary=new LinearLayout.LayoutParams(0,dp(52),1);primary.leftMargin=dp(10);actions.addView(printButton,primary);screen.addView(actions);setContentView(screen);
  }
  private void refreshDiscountModes(){discountModes.removeAllViews();discountModes.addView(modeButton("None","none",true),weight());discountModes.addView(gap());discountModes.addView(modeButton("Percent","percent",true),weight());discountModes.addView(gap());discountModes.addView(modeButton("Amount","amount",true),weight());discountField.setVisibility("none".equals(discountMode)?View.GONE:View.VISIBLE);}
  private Button modeButton(String label,String value,boolean discount){boolean selected=value.equals(discount?discountMode:paymentMode);Button b=button(label,selected?teal:Color.WHITE,selected?Color.WHITE:ink);b.setTextSize(12);b.setOnClickListener(v->{if(discount){discountMode=value;if("none".equals(value))discountValue.setText("");refreshDiscountModes();refreshTotals();}else{paymentMode=value;refreshPaymentModes();}});return b;}
  private void refreshPaymentModes(){paymentModes.removeAllViews();java.util.ArrayList<String> modes=new java.util.ArrayList<>(),labels=new java.util.ArrayList<>();modes.add("cash");labels.add("Cash");if(billing.upi){modes.add("upi");labels.add("UPI");}if(billing.card){modes.add("card");labels.add("Card");}if(billing.due){modes.add("due");labels.add("Due");}if(billing.split&&(billing.upi||billing.card||billing.due)){modes.add("split");labels.add("Split");}if(!modes.contains(paymentMode))paymentMode="cash";for(int i=0;i<modes.size();i++){if(i>0)paymentModes.addView(gap());paymentModes.addView(modeButton(labels.get(i),modes.get(i),false),weight());}buildPaymentFields();}
  private void buildPaymentFields(){updating=true;paymentFields.removeAllViews();cash=upi=card=due=cashReceived=null;if("cash".equals(paymentMode)){cashReceived=amountInput("Cash received");cashReceived.setText(money(payable));watch(cashReceived);paymentFields.addView(labeled("Cash received",cashReceived));}else if("split".equals(paymentMode)){cash=amountInput("0.00");cashReceived=amountInput("0.00");watch(cash);watch(cashReceived);paymentFields.addView(labeled("Cash portion",cash));paymentFields.addView(labeled("Cash tendered",cashReceived),top(9));if(billing.upi){upi=amountInput("0.00");watch(upi);paymentFields.addView(labeled("UPI",upi),top(9));}if(billing.card){card=amountInput("0.00");watch(card);paymentFields.addView(labeled("Card",card),top(9));}if(billing.due){due=amountInput("0.00");watch(due);paymentFields.addView(labeled("Due",due),top(9));}}else paymentFields.addView(text("Rs. "+money(payable)+" will be recorded as "+paymentMode.toUpperCase(Locale.US)+".",14,ink,true));updating=false;refreshPaymentState();}
  private void refreshTotals(){try{PosDatabase.CheckoutTotals totals=db.checkoutTotals(orderId,discountMode,value(discountValue));payable=totals.payable;subtotalText.setText("Rs. "+money(totals.subtotal));taxText.setText("Rs. "+money(totals.tax));discountText.setText("− Rs. "+money(totals.discount));totalText.setText("Rs. "+money(totals.payable));if("cash".equals(paymentMode)&&cashReceived!=null&&!cashReceived.hasFocus()){updating=true;cashReceived.setText(money(payable));updating=false;}refreshPaymentState();}catch(Exception error){showError(error);}}
  private void refreshPaymentState(){if(remainingText==null)return;double allocated=0,balance=0,dueAmount=0;if("cash".equals(paymentMode)){double received=value(cashReceived);allocated=payable;balance=Math.max(0,received-payable);remainingText.setText("Balance  Rs. "+money(balance));}else if("split".equals(paymentMode)){allocated=value(cash)+value(upi)+value(card)+value(due);dueAmount=value(due);balance=Math.max(0,value(cashReceived)-value(cash));double remaining=payable-allocated;remainingText.setText((Math.abs(remaining)<0.005?"Fully allocated":"Remaining  Rs. "+money(remaining))+"    Balance  Rs. "+money(balance));}else{allocated=payable;dueAmount="due".equals(paymentMode)?payable:0;remainingText.setText("Fully allocated");}boolean needsCustomer=dueAmount>0;customerText.setVisibility(needsCustomer?View.VISIBLE:View.GONE);if(needsCustomer)customerText.setText(customer==null?"Select customer for due":customer.name+"  •  Due Rs. "+money(customer.dueBalance));}
  private void complete(boolean print){try{PosDatabase.CheckoutRequest request=request(print);setBusy(true);new Thread(()->{try{PosDatabase.CheckoutResult result=db.finalizeOrder(orderId,request);runOnUiThread(()->openSuccess(result));}catch(Exception error){runOnUiThread(()->{setBusy(false);showError(error);});}}).start();}catch(Exception error){showError(error);}}
  private PosDatabase.CheckoutRequest request(boolean print){double cashPart=0,upiPart=0,cardPart=0,duePart=0,tendered=0;if("cash".equals(paymentMode)){cashPart=payable;tendered=value(cashReceived);if(tendered+0.005<payable)throw new IllegalStateException("Cash received is less than the bill total");}else if("upi".equals(paymentMode))upiPart=payable;else if("card".equals(paymentMode))cardPart=payable;else if("due".equals(paymentMode))duePart=payable;else{cashPart=value(cash);upiPart=value(upi);cardPart=value(card);duePart=value(due);tendered=value(cashReceived);if(Math.abs((cashPart+upiPart+cardPart+duePart)-payable)>0.005)throw new IllegalStateException("Split amounts must exactly match the bill total");if(cashPart>0&&tendered+0.005<cashPart)throw new IllegalStateException("Cash tendered is less than the cash portion");}if(duePart>0&&customer==null)throw new IllegalStateException("Select a customer for the due amount");return new PosDatabase.CheckoutRequest(discountMode,value(discountValue),customer==null?"":customer.id,cashPart,upiPart,cardPart,duePart,tendered,print);}
  private void openSuccess(PosDatabase.CheckoutResult result){if(result.printQueued)PrintDispatcher.processAsync(this);CloudSyncManager.syncAsync(this);Intent intent=new Intent(this,SaleSuccessActivity.class);intent.putExtra("orderId",orderId);intent.putExtra("printQueued",result.printQueued);startActivity(intent);finish();}
  private void setBusy(boolean busy){saveButton.setEnabled(!busy);printButton.setEnabled(!busy);printButton.setText(busy?"Saving...":"Save & Print");}

  private void showCustomerPicker(){LinearLayout box=column();box.setPadding(dp(16),dp(4),dp(16),dp(8));EditText query=input("Search name or phone",InputType.TYPE_CLASS_TEXT);box.addView(query);LinearLayout results=column();ScrollView resultScroll=new ScrollView(this);resultScroll.addView(results);box.addView(resultScroll,new LinearLayout.LayoutParams(-1,dp(220)));Button add=button("+ New Customer",Color.rgb(241,245,249),ink);box.addView(add,top(8));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Select customer").setView(box).setNegativeButton("Close",null).create();Runnable reload=()->renderCustomers(results,db.customers(query.getText().toString()),dialog);query.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){reload.run();}public void afterTextChanged(Editable e){}});add.setOnClickListener(v->showNewCustomer(dialog));dialog.setOnShowListener(v->reload.run());dialog.show();}
  private void renderCustomers(LinearLayout target,List<PosDatabase.CustomerInfo> values,AlertDialog dialog){target.removeAllViews();if(values.isEmpty()){target.addView(text("No matching customer",14,muted,false),top(16));return;}for(PosDatabase.CustomerInfo value:values){TextView row=text(value.name+"\n"+(value.phone.isEmpty()?"No phone":value.phone)+"  •  Due Rs. "+money(value.dueBalance),15,ink,true);row.setPadding(dp(12),dp(10),dp(12),dp(10));row.setBackground(shape(Color.WHITE,9,1,line));row.setOnClickListener(v->{customer=value;dialog.dismiss();refreshPaymentState();});target.addView(row,top(7));}}
  private void showNewCustomer(AlertDialog parent){LinearLayout form=column();form.setPadding(dp(18),dp(4),dp(18),0);EditText name=input("Customer name",InputType.TYPE_CLASS_TEXT),phone=input("Phone number",InputType.TYPE_CLASS_PHONE),address=input("Address",InputType.TYPE_CLASS_TEXT);form.addView(name);form.addView(phone,top(9));form.addView(address,top(9));new AlertDialog.Builder(this).setTitle("New customer").setView(form).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{try{String id=db.saveCustomer(name.getText().toString(),phone.getText().toString(),address.getText().toString());for(PosDatabase.CustomerInfo found:db.customers(phone.getText().toString()))if(found.id.equals(id)){customer=found;break;}parent.dismiss();refreshPaymentState();}catch(Exception error){showError(error);}}).show();}

  private void watch(EditText field){if(field==null)return;field.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){if(updating)return;if(field==discountValue)refreshTotals();else refreshPaymentState();}public void afterTextChanged(Editable e){}});}
  private double value(EditText field){if(field==null)return 0;try{return Math.max(0,Double.parseDouble(field.getText().toString().trim()));}catch(Exception ignored){return 0;}}
  private void showError(Throwable error){Toast.makeText(this,error.getMessage()==null?"Could not complete billing":error.getMessage(),Toast.LENGTH_LONG).show();}
  private TextView valueRow(LinearLayout parent,String label){LinearLayout row=row();row.setGravity(Gravity.CENTER_VERTICAL);row.addView(text(label,14,muted,false),new LinearLayout.LayoutParams(0,-2,1));TextView value=text("Rs. 0.00",16,ink,true);row.addView(value);parent.addView(row,top(9));return value;}
  private LinearLayout sectionHead(String title,String detail){LinearLayout box=column();box.addView(text(title,17,ink,true));box.addView(text(detail,12,muted,false),top(3));return box;}
  private LinearLayout panel(){LinearLayout p=column();p.setPadding(dp(14),dp(14),dp(14),dp(14));p.setBackground(shape(Color.WHITE,12,1,line));return p;}private LinearLayout labeled(String label,View input){LinearLayout box=column();box.addView(text(label,12,muted,true));box.addView(input,new LinearLayout.LayoutParams(-1,dp(48)));return box;}private EditText amountInput(String hint){return input(hint,InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);}private EditText input(String hint,int type){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(muted);e.setInputType(type);e.setSingleLine();e.setTextColor(ink);e.setTextSize(16);e.setPadding(dp(12),0,dp(12),0);e.setBackground(shape(Color.rgb(248,250,252),9,1,line));return e;}
  private LinearLayout column(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);return v;}private LinearLayout row(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.HORIZONTAL);return v;}private TextView text(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(Typeface.DEFAULT_BOLD);return v;}private Button button(String s,int fill,int color){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(color);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(shape(fill,9,1,line));return b;}private GradientDrawable shape(int fill,int radius,int stroke,int strokeColor){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(stroke>0)d.setStroke(dp(stroke),strokeColor);return d;}private LinearLayout.LayoutParams top(int m){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(m);return p;}private LinearLayout.LayoutParams topHeight(int m,int h){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(h));p.topMargin=dp(m);return p;}private LinearLayout.LayoutParams weight(){return new LinearLayout.LayoutParams(0,dp(44),1);}private View gap(){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(dp(6),1));return v;}private String money(double v){return String.format(Locale.US,"%.2f",v);}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density);}
}
