package com.GIHOSTINGS.giposapp;

import java.io.ByteArrayOutputStream;
import java.nio.charset.Charset;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import org.json.JSONArray;
import org.json.JSONObject;

public final class EscPosFormatter {
  private static final Charset ENCODING=Charset.forName("windows-1252");
  private EscPosFormatter(){}
  public static byte[] format(String type,String payload,int paperWidth){try{return "kot".equals(type)?kot(new JSONObject(payload),paperWidth):"report".equals(type)?report(new JSONObject(payload),paperWidth):receipt(new JSONObject(payload),paperWidth);}catch(Exception error){throw new IllegalArgumentException("Invalid print data",error);}}
  public static byte[] testPage(PosDatabase.PrinterProfile printer){Writer out=new Writer(printer.paperWidth);out.init();out.center();out.bold(true);out.size(1);out.text("GI POS MOBILE\n");out.size(0);out.bold(false);out.text("Printer test successful\n");out.text(printer.name+"\n");out.text(printer.connectionType.toUpperCase(Locale.US)+" / POS "+printer.paperWidth+"mm\n");out.rule();out.text("ABCDEFGHIJKLMNOPQRSTUVWXYZ\n0123456789  Rs. 1234.50\n");out.feedAndCut();return out.bytes();}
  private static byte[] receipt(JSONObject data,int width)throws Exception{
    Writer out=new Writer(width);out.init();businessHeader(out,data);out.rule();out.left();out.two("Bill #",String.valueOf(data.optInt("billNumber")));out.bold(true);out.two("KOT #",String.valueOf(data.optInt("kotNumber")));out.bold(false);out.two("Date",date(data.optLong("createdAt")));String table=data.optString("table");if(!table.isEmpty())out.two("Order","Dining / "+table);String operator=data.optString("operator");if(!operator.isEmpty())out.two("Operator",operator);String customer=data.optString("customer");if(!customer.isEmpty())out.two("Customer",customer);out.rule();out.columns("Item","Qty","Amount");out.rule();JSONArray items=data.getJSONArray("items");double totalQty=0;for(int i=0;i<items.length();i++){JSONObject item=items.getJSONObject(i);String name=item.optString("name");String variant=item.optString("variant");if(!variant.isEmpty())name+=" ("+variant+")";double qty=item.optDouble("quantity"),amount=item.optDouble("lineTotal");totalQty+=qty;out.item(name,quantity(qty),money(amount));}out.rule();out.two("Total quantity",quantity(totalQty));JSONObject totals=data.getJSONObject("totals");out.two("Subtotal","Rs. "+money(totals.optDouble("subtotal")));if(totals.optDouble("tax")>0)out.two("Tax","Rs. "+money(totals.optDouble("tax")));if(totals.optDouble("discount")>0)out.two("Discount","- Rs. "+money(totals.optDouble("discount")));out.rule();out.bold(true);out.size(1);out.two("TOTAL","Rs. "+money(totals.optDouble("total")));out.size(0);out.bold(false);if(totals.optDouble("due")>0)out.two("Due","Rs. "+money(totals.optDouble("due")));if(totals.optDouble("balance")>0)out.two("Balance","Rs. "+money(totals.optDouble("balance")));out.rule();out.center();String footer=data.optString("receiptFooter","Thank you. Visit again.");if(!footer.isEmpty())out.wrapped(footer);out.feedAndCut();return out.bytes();
  }
  private static void businessHeader(Writer out,JSONObject data){out.center();out.bold(true);out.size(1);out.wrapped(data.optString("businessName","GI POS"));out.size(0);out.bold(false);String address=data.optString("businessAddress");if(!address.isEmpty())out.wrapped(address);String phone=data.optString("businessPhone");if(!phone.isEmpty())out.wrapped("Phone: "+phone);String tax=data.optString("businessTaxId");if(!tax.isEmpty())out.wrapped("Tax ID: "+tax);}
  private static byte[] kot(JSONObject data,int width)throws Exception{Writer out=new Writer(width);out.init();out.center();out.bold(true);out.size(2);out.text("KOT #"+data.optInt("kotNumber")+"\n");out.size(0);out.bold(false);out.rule();out.left();out.two("Date",date(data.optLong("createdAt")));String table=data.optString("table");if(!table.isEmpty())out.two("Table",table);String operator=data.optString("operator");if(!operator.isEmpty())out.two("Operator",operator);out.rule();out.columns("Item","Qty","");out.rule();JSONArray items=data.getJSONArray("items");for(int i=0;i<items.length();i++){JSONObject item=items.getJSONObject(i);String name=item.optString("name"),variant=item.optString("variant");if(!variant.isEmpty())name+=" ("+variant+")";out.bold(true);out.item(name,quantity(item.optDouble("quantity")),"");out.bold(false);String note=item.optString("note");if(!note.isEmpty())out.wrapped("  "+note);}out.rule();out.center();out.bold(true);out.text("END OF KOT\n");out.bold(false);out.feedAndCut();return out.bytes();}
  private static byte[] report(JSONObject data,int width)throws Exception{Writer out=new Writer(width);out.init();out.center();out.bold(true);out.size(1);out.wrapped(data.optString("businessName","GI POS"));out.size(0);out.text("SALES REPORT\n");out.bold(false);out.text(day(data.optLong("from"))+"\n");out.rule();out.left();out.two("Total sales","Rs. "+money(data.optDouble("sales")));out.two("Paid bills",String.valueOf(data.optInt("bills")));out.two("Total quantity",quantity(data.optDouble("totalQuantity")));if(data.optDouble("tax")>0)out.two("Tax","Rs. "+money(data.optDouble("tax")));if(data.optDouble("discount")>0)out.two("Discount","Rs. "+money(data.optDouble("discount")));if(data.optDouble("due")>0)out.two("Due","Rs. "+money(data.optDouble("due")));out.rule();out.bold(true);out.text("PAYMENTS\n");out.bold(false);if(data.optDouble("cash")>0)out.two("Cash","Rs. "+money(data.optDouble("cash")));if(data.optDouble("upi")>0)out.two("UPI","Rs. "+money(data.optDouble("upi")));if(data.optDouble("card")>0)out.two("Card","Rs. "+money(data.optDouble("card")));JSONArray items=data.optJSONArray("items");if(items!=null&&items.length()>0){out.rule();out.bold(true);out.columns("Item","Qty","Amount");out.bold(false);out.rule();for(int i=0;i<items.length();i++){JSONObject item=items.getJSONObject(i);out.item(item.optString("name"),quantity(item.optDouble("quantity")),money(item.optDouble("amount")));}}out.rule();out.center();out.text("End of report\n");out.feedAndCut();return out.bytes();}
  private static String date(long timestamp){return new SimpleDateFormat("dd/MM/yyyy, hh:mm a",Locale.US).format(new Date(timestamp));}private static String day(long timestamp){return new SimpleDateFormat("dd MMM yyyy",Locale.US).format(new Date(timestamp));}private static String money(double value){return String.format(Locale.US,"%.2f",value);}private static String quantity(double value){return Math.rint(value)==value?String.valueOf((long)value):String.format(Locale.US,"%.2f",value);}
  private static final class Writer {final int columns;final ByteArrayOutputStream out=new ByteArrayOutputStream();Writer(int width){columns=width<=58?32:48;}void raw(int...values){for(int value:values)out.write(value);}void init(){raw(27,64);raw(27,116,16);}void left(){raw(27,97,0);}void center(){raw(27,97,1);}void bold(boolean on){raw(27,69,on?1:0);}void size(int scale){raw(29,33,scale==2?34:scale==1?17:0);}void text(String value){byte[] bytes=value.getBytes(ENCODING);out.write(bytes,0,bytes.length);}void wrapped(String value){for(String line:wrap(value,columns))text(line+"\n");}void rule(){left();text(repeat('-',columns)+"\n");}void two(String left,String right){this.left();int room=Math.max(1,columns-right.length()-1);String[] lines=wrap(left,room);for(int i=0;i<lines.length;i++){if(i==lines.length-1){String l=lines[i];text(l+repeat(' ',Math.max(1,columns-l.length()-right.length()))+right+"\n");}else text(lines[i]+"\n");}}void columns(String name,String qty,String amount){left();int amountWidth=columns<=32?9:12,qtyWidth=5,nameWidth=columns-amountWidth-qtyWidth;String n=trim(name,nameWidth),q=trim(qty,qtyWidth),a=trim(amount,amountWidth);text(padRight(n,nameWidth)+padLeft(q,qtyWidth)+padLeft(a,amountWidth)+"\n");}void item(String name,String qty,String amount){int amountWidth=columns<=32?9:12,qtyWidth=5,nameWidth=columns-amountWidth-qtyWidth;String[] lines=wrap(name,nameWidth);for(int i=0;i<lines.length;i++){String q=i==0?qty:"",a=i==0?amount:"";text(padRight(lines[i],nameWidth)+padLeft(q,qtyWidth)+padLeft(a,amountWidth)+"\n");}}void feedAndCut(){text("\n\n\n");raw(29,86,66,0);}byte[] bytes(){return out.toByteArray();}}
  private static String[] wrap(String value,int width){String clean=value==null?"":value.trim();if(clean.isEmpty())return new String[]{""};java.util.ArrayList<String> lines=new java.util.ArrayList<>();while(clean.length()>width){int cut=clean.lastIndexOf(' ',width);if(cut<1)cut=width;lines.add(clean.substring(0,cut).trim());clean=clean.substring(cut).trim();}lines.add(clean);return lines.toArray(new String[0]);}private static String repeat(char c,int count){StringBuilder b=new StringBuilder();for(int i=0;i<count;i++)b.append(c);return b.toString();}private static String padRight(String v,int width){return trim(v,width)+repeat(' ',Math.max(0,width-trim(v,width).length()));}private static String padLeft(String v,int width){String t=trim(v,width);return repeat(' ',Math.max(0,width-t.length()))+t;}private static String trim(String v,int width){return v.length()<=width?v:v.substring(0,width);}
}
