package com.GIHOSTINGS.giposapp;

import android.app.AlertDialog;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.net.Uri;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ImageView;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;
import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import java.util.ArrayList;
import java.util.List;

public class ItemEditorActivity extends InsetActivity {
  private final int ink=Color.rgb(18,32,51),red=Color.rgb(199,22,55),muted=Color.rgb(99,115,138),teal=Color.rgb(8,127,140),line=Color.rgb(217,226,236);
  private PosDatabase db; private String productId="",priceMode="fixed"; private PosDatabase.ProductInfo existing;
  private EditText name,alias,price,tax,description,kotDescription,kotRoute; private Spinner category,gstMode,gstType; private CheckBox available,favorite,special,hot;
  private ImageView imagePreview; private String imageUri="";
  private LinearLayout variantSection,variantRows,priceSection,modeBar; private final ArrayList<VariantEditor> variantEditors=new ArrayList<>(); private List<PosDatabase.CategoryInfo> categories=new ArrayList<>();
  private final ActivityResultLauncher<String[]> imagePicker=registerForActivityResult(new ActivityResultContracts.OpenDocument(),uri->{if(uri==null)return;try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}imageUri=uri.toString();showImage();});

  @Override public void onCreate(Bundle saved){super.onCreate(saved);if(!requireFeature("menuManagement"))return;db=PosDatabase.get(this);productId=getIntent().getStringExtra("productId");if(productId==null)productId="";existing=productId.isEmpty()?null:db.product(productId);build();}
  private void build(){
    LinearLayout page=column();page.setPadding(dp(16),dp(14),dp(16),dp(30));page.setBackgroundColor(Color.rgb(244,247,250));
    LinearLayout head=row();head.setGravity(Gravity.CENTER_VERTICAL);Button back=button("‹",Color.WHITE,ink);back.setTextSize(22);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout title=column();title.setPadding(dp(12),0,0,0);title.addView(text(existing==null?"Add Item":"Edit Item",24,ink,true));title.addView(text("Menu details, pricing, tax, and kitchen notes",12,muted,false));head.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button save=button("Save",red,Color.WHITE);save.setOnClickListener(v->save());head.addView(save,new LinearLayout.LayoutParams(dp(92),dp(44)));page.addView(head);
    page.addView(sectionTitle("Item details"),top(20));LinearLayout details=panel();name=input("Item name",InputType.TYPE_CLASS_TEXT);alias=input("Alias / search name",InputType.TYPE_CLASS_TEXT);details.addView(field("Item name",name));details.addView(field("Alias",alias),top(12));
    categories=db.categories();category=new Spinner(this);setCategoryAdapter();LinearLayout categoryRow=row();categoryRow.addView(category,new LinearLayout.LayoutParams(0,dp(50),1));Button addCategory=button("+",Color.rgb(241,245,249),teal);addCategory.setOnClickListener(v->addCategory());LinearLayout.LayoutParams addParams=new LinearLayout.LayoutParams(dp(52),dp(50));addParams.leftMargin=dp(8);categoryRow.addView(addCategory,addParams);details.addView(labeled("Category",categoryRow),top(12));page.addView(details,top(8));

    page.addView(sectionTitle("Item image"),top(18));LinearLayout media=panel();imagePreview=new ImageView(this);imagePreview.setScaleType(ImageView.ScaleType.CENTER_CROP);imagePreview.setBackground(shape(Color.rgb(241,245,249),10,1,line));media.addView(imagePreview,new LinearLayout.LayoutParams(-1,dp(150)));LinearLayout mediaActions=row();Button chooseImage=button("Choose image",Color.rgb(229,247,249),teal);chooseImage.setOnClickListener(v->imagePicker.launch(new String[]{"image/*"}));mediaActions.addView(chooseImage,new LinearLayout.LayoutParams(0,dp(44),1));Button removeImage=button("Remove",Color.rgb(255,241,242),red);removeImage.setOnClickListener(v->{imageUri="";showImage();});LinearLayout.LayoutParams removeParams=new LinearLayout.LayoutParams(dp(100),dp(44));removeParams.leftMargin=dp(8);mediaActions.addView(removeImage,removeParams);media.addView(mediaActions,top(10));page.addView(media,top(8));

    page.addView(sectionTitle("Pricing"),top(18));LinearLayout pricing=panel();modeBar=row();pricing.addView(modeBar);priceSection=column();price=input("0.00",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);priceSection.addView(field("Selling price",price));pricing.addView(priceSection,top(12));variantSection=column();variantRows=column();variantSection.addView(variantRows);Button addVariant=button("+ Add another size",Color.rgb(241,245,249),ink);addVariant.setOnClickListener(v->addVariant(null));variantSection.addView(addVariant,top(8));pricing.addView(variantSection,top(12));page.addView(pricing,top(8));

    page.addView(sectionTitle("Tax"),top(18));LinearLayout taxPanel=panel();tax=input("0",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);taxPanel.addView(field("GST / VAT rate (%)",tax));gstMode=spinner(new String[]{"Exclusive tax","Inclusive tax"});gstType=spinner(new String[]{"CGST + SGST","IGST","VAT","No tax split"});taxPanel.addView(labeled("Calculation",gstMode),top(12));taxPanel.addView(labeled("Tax type",gstType),top(12));page.addView(taxPanel,top(8));

    page.addView(sectionTitle("Sale visibility"),top(18));LinearLayout flags=panel();available=check("Available for sale",true);favorite=check("Favourite",false);special=check("Special",false);hot=check("Hot item",false);flags.addView(available);flags.addView(favorite);flags.addView(special);flags.addView(hot);page.addView(flags,top(8));

    page.addView(sectionTitle("Kitchen & notes"),top(18));LinearLayout notes=panel();description=multiline("Item description");kotDescription=multiline("KOT description shown below this item");kotRoute=input("Kitchen group / printer route",InputType.TYPE_CLASS_TEXT);notes.addView(field("Description",description));notes.addView(field("KOT description",kotDescription),top(12));notes.addView(field("KOT route",kotRoute),top(12));page.addView(notes,top(8));
    ScrollView scroll=new ScrollView(this);scroll.addView(page);setContentView(scroll);bind();
  }
  private void bind(){refreshModeButtons();if(existing==null){tax.setText("0");showImage();return;}name.setText(existing.name);alias.setText(existing.alias);price.setText(money(existing.price));tax.setText(money(existing.taxRate));description.setText(existing.description);kotDescription.setText(existing.kotDescription);kotRoute.setText(existing.kotRoute);available.setChecked(existing.available);favorite.setChecked(existing.favorite);special.setChecked(existing.special);hot.setChecked(existing.hotItem);imageUri=existing.imageUri;showImage();priceMode=existing.priceMode;gstMode.setSelection("inclusive".equals(existing.gstMode)?1:0);gstType.setSelection(typeIndex(existing.gstType));for(int i=0;i<categories.size();i++)if(categories.get(i).id.equals(existing.categoryId)){category.setSelection(i);break;}for(PosDatabase.VariantInfo variant:existing.variants)addVariant(variant);refreshModeButtons();}
  private void showImage(){if(imagePreview==null)return;if(imageUri.isEmpty()){imagePreview.setImageDrawable(null);imagePreview.setContentDescription("No item image selected");return;}try{imagePreview.setImageURI(Uri.parse(imageUri));imagePreview.setContentDescription("Selected item image");}catch(Exception ignored){imageUri="";imagePreview.setImageDrawable(null);}}
  private void refreshModeButtons(){modeBar.removeAllViews();modeBar.addView(mode("Fixed price","fixed"),weight());modeBar.addView(space());modeBar.addView(mode("Variants","variants"),weight());modeBar.addView(space());modeBar.addView(mode("Ask price","manual"),weight());priceSection.setVisibility("fixed".equals(priceMode)?View.VISIBLE:View.GONE);variantSection.setVisibility("variants".equals(priceMode)?View.VISIBLE:View.GONE);}
  private Button mode(String label,String value){boolean selected=value.equals(priceMode);Button b=button(label,selected?teal:Color.WHITE,selected?Color.WHITE:ink);b.setOnClickListener(v->{priceMode=value;if("variants".equals(value)&&variantEditors.isEmpty())addVariant(null);refreshModeButtons();});return b;}
  private void addVariant(PosDatabase.VariantInfo value){VariantEditor editor=new VariantEditor(value);variantEditors.add(editor);variantRows.addView(editor.view,top(8));}
  private void removeVariant(VariantEditor editor){variantEditors.remove(editor);variantRows.removeView(editor.view);}
  private void addCategory(){EditText input=input("Category name",InputType.TYPE_CLASS_TEXT);new AlertDialog.Builder(this).setTitle("New category").setView(input).setNegativeButton("Cancel",null).setPositiveButton("Add",(d,w)->{String value=input.getText().toString().trim();if(!value.isEmpty()){String id=db.addCategory(value);categories=db.categories();setCategoryAdapter();for(int i=0;i<categories.size();i++)if(categories.get(i).id.equals(id)){category.setSelection(i);break;}}}).show();}
  private void setCategoryAdapter(){ArrayAdapter<PosDatabase.CategoryInfo> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,categories);category.setAdapter(adapter);}
  private void save(){String itemName=name.getText().toString().trim();if(itemName.isEmpty()){name.setError("Item name is required");name.requestFocus();return;}if(categories.isEmpty()){Toast.makeText(this,"Add a category first",Toast.LENGTH_SHORT).show();return;}double base=number(price,0),rate=number(tax,0);ArrayList<PosDatabase.VariantInfo> variants=new ArrayList<>();if("variants".equals(priceMode)){for(VariantEditor editor:variantEditors){String variantName=editor.name.getText().toString().trim();if(variantName.isEmpty()){editor.name.setError("Size name is required");return;}variants.add(new PosDatabase.VariantInfo(editor.id,variantName,number(editor.price,0)));}if(variants.isEmpty()){Toast.makeText(this,"Add at least one size",Toast.LENGTH_SHORT).show();return;}}
    PosDatabase.CategoryInfo selected=(PosDatabase.CategoryInfo)category.getSelectedItem();String mode=gstMode.getSelectedItemPosition()==1?"inclusive":"exclusive";String type=new String[]{"cgst_sgst","igst","vat","none"}[gstType.getSelectedItemPosition()];PosDatabase.ProductInfo value=new PosDatabase.ProductInfo(productId,selected.id,selected.name,itemName,alias.getText().toString(),base,rate,available.isChecked(),description.getText().toString(),kotDescription.getText().toString(),priceMode,mode,type,favorite.isChecked(),special.isChecked(),hot.isChecked(),kotRoute.getText().toString(),imageUri,variants);db.saveProduct(value,variants);Toast.makeText(this,"Item saved",Toast.LENGTH_SHORT).show();finish();}

  private final class VariantEditor {final String id;final LinearLayout view;final EditText name,price;VariantEditor(PosDatabase.VariantInfo value){id=value==null?"":value.id;view=row();view.setGravity(Gravity.CENTER_VERTICAL);name=input("Size name",InputType.TYPE_CLASS_TEXT);price=input("Price",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);if(value!=null){name.setText(value.name);price.setText(money(value.price));}view.addView(name,new LinearLayout.LayoutParams(0,dp(50),1));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(dp(110),dp(50));pp.leftMargin=dp(8);view.addView(price,pp);Button remove=button("×",Color.rgb(255,241,242),red);remove.setOnClickListener(v->removeVariant(this));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(dp(48),dp(50));rp.leftMargin=dp(8);view.addView(remove,rp);}}
  private int typeIndex(String value){if("igst".equals(value))return 1;if("vat".equals(value))return 2;if("none".equals(value))return 3;return 0;}private double number(EditText input,double fallback){try{return Math.max(0,Double.parseDouble(input.getText().toString().trim()));}catch(Exception ignored){return fallback;}}
  private Spinner spinner(String[] values){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,values));s.setBackground(shape(Color.rgb(248,250,252),9,1,line));s.setPadding(dp(10),0,dp(8),0);return s;}
  private CheckBox check(String label,boolean checked){CheckBox c=new CheckBox(this);c.setText(label);c.setTextSize(15);c.setTextColor(ink);c.setChecked(checked);c.setMinHeight(dp(44));return c;}private EditText multiline(String hint){EditText e=input(hint,InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);e.setSingleLine(false);e.setMinHeight(dp(80));e.setGravity(Gravity.TOP);e.setPadding(dp(12),dp(10),dp(12),dp(10));return e;}
  private EditText input(String hint,int type){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(muted);e.setInputType(type);e.setSingleLine();e.setTextSize(15);e.setTextColor(ink);e.setPadding(dp(12),0,dp(12),0);e.setBackground(shape(Color.rgb(248,250,252),9,1,line));return e;}
  private LinearLayout field(String label,View input){return labeled(label,input);}private LinearLayout labeled(String label,View input){LinearLayout box=column();box.addView(text(label,12,muted,true));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,input.getLayoutParams()==null?dp(50):input.getLayoutParams().height);p.topMargin=dp(5);box.addView(input,p);return box;}
  private LinearLayout panel(){LinearLayout p=column();p.setPadding(dp(14),dp(14),dp(14),dp(14));p.setBackground(shape(Color.WHITE,12,1,line));return p;}private TextView sectionTitle(String value){return text(value,16,ink,true);}
  private LinearLayout column(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);return v;}private LinearLayout row(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.HORIZONTAL);return v;}private TextView text(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(Typeface.DEFAULT_BOLD);return v;}private Button button(String s,int fill,int color){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(color);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(shape(fill,9,1,line));return b;}
  private GradientDrawable shape(int fill,int radius,int stroke,int strokeColor){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(stroke>0)d.setStroke(dp(stroke),strokeColor);return d;}private LinearLayout.LayoutParams top(int m){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(m);return p;}private LinearLayout.LayoutParams weight(){return new LinearLayout.LayoutParams(0,dp(46),1);}private View space(){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(dp(7),1));return v;}private String money(double v){return String.format(java.util.Locale.US,"%.2f",v);}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density);}
}
