package com.GIHOSTINGS.giposapp;

import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;
import androidx.activity.OnBackPressedCallback;
import java.util.Locale;

public class SaleSuccessActivity extends InsetActivity {
  private final int ink=Color.rgb(18,32,51),red=Color.rgb(199,22,55),muted=Color.rgb(99,115,138),teal=Color.rgb(8,127,140),line=Color.rgb(217,226,236);
  private String orderId;private PosDatabase db;
  @Override public void onCreate(Bundle saved){super.onCreate(saved);if(!requireFeature("billing"))return;db=PosDatabase.get(this);orderId=getIntent().getStringExtra("orderId");getOnBackPressedDispatcher().addCallback(this,new OnBackPressedCallback(true){@Override public void handleOnBackPressed(){openTables();}});build();}
  private void build(){PosDatabase.OrderInfo order=db.orderInfo(orderId);if(order==null){openTables();return;}LinearLayout root=column();root.setGravity(Gravity.CENTER_HORIZONTAL);root.setPadding(dp(22),dp(34),dp(22),dp(24));root.setBackgroundColor(Color.rgb(244,247,250));TextView check=text("✓",34,Color.WHITE,true);check.setGravity(Gravity.CENTER);check.setBackground(shape(teal,40,0,teal));root.addView(check,new LinearLayout.LayoutParams(dp(78),dp(78)));root.addView(text(order.due>0?"Bill saved with due":"Payment complete",26,ink,true),topWrap(18));root.addView(text("The full transaction is safely stored on this device.",14,muted,false),topWrap(5));LinearLayout card=column();card.setPadding(dp(18),dp(18),dp(18),dp(18));card.setBackground(shape(Color.WHITE,13,1,line));card.addView(pair("Bill number",order.billPeriod+" / "+order.billNumber));card.addView(pair("KOT number",order.kotPeriod+" / "+order.kotNumber),top(9));card.addView(pair("Table",order.tableName.isEmpty()?"Direct sale":order.tableName),top(9));if(!order.customerName.isEmpty())card.addView(pair("Customer",order.customerName),top(9));card.addView(pair("Total","Rs. "+money(order.total)),top(12));card.addView(pair("Received","Rs. "+money(order.received)),top(9));if(order.due>0)card.addView(pair("Due","Rs. "+money(order.due)),top(9));if(order.balance>0)card.addView(pair("Balance","Rs. "+money(order.balance)),top(9));root.addView(card,top(22));boolean queued=getIntent().getBooleanExtra("printQueued",false);TextView printState=text(queued?"Receipt queued for printing":"Receipt is ready to print",13,queued?teal:muted,true);root.addView(printState,topWrap(14));Button print=button(queued?"Print queued":"Print Receipt",Color.WHITE,ink);print.setEnabled(!queued);print.setOnClickListener(v->{boolean added=db.queueReceiptPrint(orderId);PrintDispatcher.processAsync(this);print.setEnabled(false);print.setText("Print queued");Toast.makeText(this,added?"Receipt queued":"Receipt is already queued",Toast.LENGTH_SHORT).show();});root.addView(print,top(18));Button next=button("New Order",red,Color.WHITE);next.setOnClickListener(v->openTables());root.addView(next,top(10));Button home=button("Home",Color.rgb(241,245,249),ink);home.setOnClickListener(v->openHome());root.addView(home,top(10));setContentView(root);}
  private LinearLayout pair(String label,String value){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.addView(text(label,13,muted,false),new LinearLayout.LayoutParams(0,-2,1));r.addView(text(value,15,ink,true));return r;}
  private void openTables(){Intent intent=new Intent(this,TableActivity.class);intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);startActivity(intent);finish();}private void openHome(){Intent intent=new Intent(this,DashboardActivity.class);intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);startActivity(intent);finish();}
  private LinearLayout column(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);return v;}private LinearLayout row(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.HORIZONTAL);return v;}private TextView text(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(Typeface.DEFAULT_BOLD);v.setGravity(Gravity.CENTER);return v;}private Button button(String s,int fill,int color){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(color);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(shape(fill,10,1,line));return b;}private GradientDrawable shape(int fill,int radius,int stroke,int strokeColor){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(stroke>0)d.setStroke(dp(stroke),strokeColor);return d;}private LinearLayout.LayoutParams top(int m){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(m);return p;}private LinearLayout.LayoutParams topWrap(int m){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.topMargin=dp(m);return p;}private String money(double value){return String.format(Locale.US,"%.2f",value);}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density);}
}
